<?php

namespace Database\Seeders;

use App\Models\Affix;
use App\Models\AffixGroup\AffixGroup;
use App\Models\AffixGroup\AffixGroupCoupling;
use App\SeederHelpers\Traits\LoadsSeasonData;
use Exception;
use Illuminate\Database\Seeder;

class AffixSeeder extends Seeder implements TableSeederInterface
{
    use LoadsSeasonData;

    /**
     * Seeds affixes and the weekly affix rotation from database/seeders/seasondata/.
     *
     * Both files are generated by `php artisan mapping:save` - do not hand-edit them. Affixes and affix
     * groups are managed through the admin panel; export, then commit the resulting diff.
     *
     * Affix groups are stored in the game's rotation order. Which week a season *starts* on is
     * seasons.start_affix_group_index, which SeasonAffixGroupService applies at read time - so the
     * rotation must never be rotated by hand to compensate. Beyond being unnecessary, affix_groups.id
     * is referenced by user data (dungeon_route_affix_groups, which has no foreign key) and is used
     * arithmetically by App\Logic\MDT\Conversion, so reordering silently re-points saved routes at
     * different affixes. That is why the ids are exported explicitly rather than left to insert order.
     *
     * @throws Exception
     */
    public function run(): void
    {
        $seededAffixIds = $this->seedAffixes();

        $this->seedAffixGroups($seededAffixIds);
    }

    /**
     * @return array<int, int> The seeded affix ids, keyed by id, so couplings can be validated against them.
     * @throws Exception
     */
    private function seedAffixes(): array
    {
        $affixAttributes = [];
        $seededAffixIds  = [];

        foreach ($this->loadSeasonDataFile('affixes.json') as $affixData) {
            $affixAttributes[] = [
                'id'          => $affixData['id'],
                'key'         => $affixData['key'],
                'affix_id'    => $affixData['affix_id'],
                'name'        => $affixData['name'],
                'description' => $affixData['description'],
            ];

            $seededAffixIds[$affixData['id']] = $affixData['id'];
        }

        Affix::from(DatabaseSeeder::getTempTableName(Affix::class))
            ->insert($affixAttributes);

        return $seededAffixIds;
    }

    /**
     * @param  array<int, int> $seededAffixIds
     * @throws Exception
     */
    private function seedAffixGroups(array $seededAffixIds): void
    {
        $affixGroupAttributes          = [];
        $affixGroupCouplingsAttributes = [];

        foreach ($this->loadSeasonDataFile('affix_groups.json') as $affixGroupData) {
            $affixGroupAttributes[] = [
                'id'             => $affixGroupData['id'],
                'season_id'      => $affixGroupData['season_id'],
                'expansion_id'   => $affixGroupData['expansion_id'],
                'seasonal_index' => $affixGroupData['seasonal_index'],
                'confirmed'      => $affixGroupData['confirmed'],
            ];

            // The order of this array is the display order: it becomes the insertion order, which in turn
            // becomes the affix_group_couplings.id order that AffixGroupBase::affixes() sorts on.
            foreach ($affixGroupData['affixes'] as $affixGroupCouplingData) {
                $affixId = $affixGroupCouplingData['affix_id'];

                if (!isset($seededAffixIds[$affixId])) {
                    throw new Exception(sprintf(
                        'Affix group %d references affix %d, which does not exist in affixes.json',
                        $affixGroupData['id'],
                        $affixId,
                    ));
                }

                $affixGroupCouplingsAttributes[] = [
                    'affix_id'       => $affixId,
                    'affix_group_id' => $affixGroupData['id'],
                    'key_level'      => $affixGroupCouplingData['key_level'],
                ];
            }
        }

        AffixGroup::from(DatabaseSeeder::getTempTableName(AffixGroup::class))
            ->insert($affixGroupAttributes);
        AffixGroupCoupling::from(DatabaseSeeder::getTempTableName(AffixGroupCoupling::class))
            ->insert($affixGroupCouplingsAttributes);
    }

    public static function getAffectedModelClasses(): array
    {
        return [
            Affix::class,
            AffixGroup::class,
            AffixGroupCoupling::class,
        ];
    }

    public static function getAffectedEnvironments(): ?array
    {
        // All environments
        return null;
    }
}
