<?php

namespace Database\Seeders;

use App\Models\Season;
use App\Models\SeasonDungeon;
use App\SeederHelpers\Traits\LoadsSeasonData;
use Exception;
use Illuminate\Database\Seeder;

class SeasonsSeeder extends Seeder implements TableSeederInterface
{
    use LoadsSeasonData;

    /**
     * Seeds seasons and their dungeon assignments from database/seeders/seasondata/.
     *
     * Both files are generated by `php artisan mapping:save` - do not hand-edit them. Seasons are managed
     * through the admin panel; export, then commit the resulting diff.
     *
     * start_affix_group_index is the 0-based offset into the season's affix groups that week 0 resolves
     * to; SeasonAffixGroupService applies it at read time. It must stay within affix_group_count, and
     * affix_group_count must match the number of affix groups actually seeded for the season.
     *
     * @throws Exception
     */
    public function run(): void
    {
        $seasonAttributes = [];

        foreach ($this->loadSeasonDataFile('seasons.json') as $seasonData) {
            $seasonAttributes[] = [
                'id'                      => $seasonData['id'],
                'expansion_id'            => $seasonData['expansion_id'],
                'seasonal_affix_id'       => $seasonData['seasonal_affix_id'],
                'index'                   => $seasonData['index'],
                'start'                   => $seasonData['start'],
                'presets'                 => $seasonData['presets'],
                'affix_group_count'       => $seasonData['affix_group_count'],
                'start_affix_group_index' => $seasonData['start_affix_group_index'],
                'key_level_min'           => $seasonData['key_level_min'],
                'key_level_max'           => $seasonData['key_level_max'],
                'item_level_min'          => $seasonData['item_level_min'],
                'item_level_max'          => $seasonData['item_level_max'],
            ];
        }

        $seasonDungeonAttributes = [];

        foreach ($this->loadSeasonDataFile('season_dungeons.json') as $seasonDungeonData) {
            $seasonDungeonAttributes[] = [
                'id'         => $seasonDungeonData['id'],
                'season_id'  => $seasonDungeonData['season_id'],
                'dungeon_id' => $seasonDungeonData['dungeon_id'],
            ];
        }

        Season::from(DatabaseSeeder::getTempTableName(Season::class))
            ->insert($seasonAttributes);
        SeasonDungeon::from(DatabaseSeeder::getTempTableName(SeasonDungeon::class))
            ->insert($seasonDungeonAttributes);
    }

    public static function getAffectedModelClasses(): array
    {
        return [
            Season::class,
            SeasonDungeon::class,
        ];
    }

    public static function getAffectedEnvironments(): ?array
    {
        // All environments
        return null;
    }
}
