<?php

namespace App\Http\Models\Request\CombatLog\Route;

use App\Http\Models\Request\RequestModel;
use Illuminate\Contracts\Support\Arrayable;
use Override;

/**
 * @OA\Schema(schema="CombatLogRouteSettings")
 * @OA\Property(property="temporary", type="boolean", nullable=true)
 * @OA\Property(property="debugIcons", type="boolean", nullable=true)
 * @OA\Property(property="mappingVersion", type="integer", nullable=true)
 * @OA\Property(property="publicKey", type="string", nullable=true,description="Allows for regeneration of a route by passing the original route's public key. This route MUST be generated by ARC to work.")
 */
/**
 * @implements Arrayable<string, mixed>
 */
class CombatLogRouteSettingsRequestModel extends RequestModel implements Arrayable
{
    public function __construct(
        public ?bool   $temporary = null,
        public ?bool   $debugIcons = null,
        public ?int    $mappingVersion = null,
        public ?string $publicKey = null,
    ) {
    }

    #[Override]
    public function toArray(): array
    {
        // Make sure that mappingVersion is not echoed if it is null
        // This is important for backwards compatibility
        return array_filter([
            'temporary'      => $this->temporary,
            'debugIcons'     => $this->debugIcons,
            'mappingVersion' => $this->mappingVersion,
            'publicKey'      => $this->publicKey,
        ], fn($value) => !is_null($value));
    }
}
