version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target-branch: "development"
    labels:
      - "security"
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    target-branch: "development"
    labels:
      - "security"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: "development"
    labels:
      - "security"
