version: "3.7"
services:
  app-base:
    build:
      context: docker-compose/app-base
      dockerfile: Dockerfile
    image: keystone.guru-app-base

  app:
    build:
      context: docker-compose/app
      dockerfile: Dockerfile
    image: keystone.guru
    container_name: keystone.guru-app
    depends_on: 
      - db
      - db-combatlog
      - redis
    restart: no
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/app/usr/local/etc/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - keystone.guru

  horizon:
    image: keystone.guru-app-base
    container_name: keystone.guru-horizon
    depends_on:
      - db
      - db-combatlog
      - redis
    restart: no
    volumes:
      - ./:/var/www
    command:
      - /usr/local/bin/php74 /var/www/artisan horizon
    networks:
      - keystone.guru

  laravel-echo-server:
    build:
      context: docker-compose/laravel-echo-server
      dockerfile: Dockerfile
    image: laravel-echo-server
    container_name: keystone.guru-laravel-echo-server
    depends_on:
      - redis
    restart: no
    ports:
      - "6001:6001"
    volumes:
      - ./:/app
    networks:
      - keystone.guru

  db:
    image: mysql:5.7
    container_name: keystone.guru-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - keystone.guru
  
  db-combatlog:
    image: mysql:5.7
    container_name: keystone.guru-db-combatlog
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_COMBATLOG_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_COMBATLOG_PASSWORD}
      MYSQL_PASSWORD: ${DB_COMBATLOG_PASSWORD}
      MYSQL_USER: ${DB_COMBATLOG_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./docker-compose/mysql-combatlog:/var/lib/mysql
    networks:
      - keystone.guru

  nginx:
    image: nginx:alpine
    container_name: keystone.guru-nginx
    restart: unless-stopped
    depends_on:
      # It complains about php-fpm not being there if this is not running first
      - app
      - laravel-echo-server
    ports:
      - "8008:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - keystone.guru

  redis:
    image: redis:alpine
    container_name: keystone.guru-redis
    ports:
     - "6379:6379"
    volumes:
     - ./docker-compose/redis-data:/var/lib/redis
    networks:
      - keystone.guru

networks:
  keystone.guru:
    driver: bridge
