require('dotenv').config();

const path = require('path');
const fs = require('node:fs');
const { GitRevisionPlugin } = require('git-revision-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// ---------------------------------------------------------------------------
// Version
// ---------------------------------------------------------------------------
let version;
let extraPlugins = [];

if (process.env.npm_config_output_version) {
    version = process.env.npm_config_output_version;
} else {
    const gitRevisionPlugin = new GitRevisionPlugin({ versionCommand: 'rev-list HEAD -1' });
    extraPlugins.push(gitRevisionPlugin);
    version = gitRevisionPlugin.version();

    fs.writeFile('version', version, (err) => {
        if (err) { console.error(err); }
    });
}

// ---------------------------------------------------------------------------
// Per-locale language bundle entries
// ---------------------------------------------------------------------------
const langEntries = {};
try {
    const langRoot = path.resolve(__dirname, 'lang');
    const generatedDir = path.resolve(__dirname, 'resources/assets/js/generated/lang');

    if (fs.existsSync(langRoot)) {
        fs.mkdirSync(generatedDir, { recursive: true });

        const locales = fs.readdirSync(langRoot)
            .filter(entry => fs.statSync(path.join(langRoot, entry)).isDirectory());

        locales.forEach(locale => {
            if (process.env.APP_ENV === 'local' && locale !== 'en_US') {
                return;
            }

            const entryFile = path.join(generatedDir, `lang-${locale}.js`);
            const content = `// Auto-generated by webpack.config.js — do not edit
// Aggregates all PHP translation files for locale ${locale}
const req = require.context('../../../../../lang/${locale}', false, /\\.php$/);
const messages = {};
req.keys().forEach(key => {
  const name = key.replace('./','').replace('.php','');
  messages['${locale}.' + name] = req(key);
});
if (typeof window !== 'undefined' && window.Lang) {
  if (window.lang && typeof window.lang.setMessages === 'function') {
    window.lang.setMessages(messages);
  } else {
    window.lang = new window.Lang({messages});
  }
}
export default messages;
`;
            fs.writeFileSync(entryFile, content);
            langEntries[`js/lang-${locale}-${version}`] = entryFile;
        });
    }
} catch (e) {
    console.warn('Failed to generate per-locale language bundles:', e);
}

// ---------------------------------------------------------------------------
// Webpack configuration
// ---------------------------------------------------------------------------
module.exports = (env, argv) => {
    const isProd = argv.mode === 'production';

    return {
        entry: {
            [`js/app-${version}`]: './resources/assets/js/app.js',
            [`css/app-${version}`]: './resources/assets/sass/app.scss',
            [`css/theme-${version}`]: './resources/assets/sass/theme/theme.scss',
            [`css/home-${version}`]: './resources/assets/sass/home.scss',
            [`css/custom-compiled-${version}`]: './resources/assets/sass/custom/custom.scss',
            [`css/assets-compiled-${version}`]: './resources/assets/sass/custom/assets/assets.scss',
            ...langEntries,
        },
        output: {
            path: path.resolve(__dirname, 'public'),
            filename: '[name].js',
            publicPath: '/',
        },
        devtool: 'source-map',
        watchOptions: {
            ignored: ['**/node_modules/**', '**/vendor/**', '**/storage/**'],
            poll: 2000,
        },
        resolve: {
            alias: {
                // Handlebars has a bug which requires this: https://github.com/wycats/handlebars.js/issues/1174
                handlebars: 'handlebars/dist/handlebars.min.js',
            },
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: [['@babel/preset-env', { targets: '> 0.5%, last 2 versions, not dead' }]],
                        },
                    },
                },
                {
                    // Matches all PHP or JSON files in `lang` directory.
                    test: /lang.+\.(php|json)$/,
                    loader: 'laravel-localization-loader',
                },
                {
                    test: /\.s[ac]ss$/i,
                    use: [
                        MiniCssExtractPlugin.loader,
                        {
                            loader: 'css-loader',
                            options: {
                                // processCssUrls: false equivalent — do not rewrite url() or @import paths
                                url: false,
                                import: false,
                            },
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                additionalData: `$asset-url: "${process.env.ASSETS_BASE_URL}";`,
                            },
                        },
                    ],
                },
            ],
        },
        plugins: [
            // Remove the empty .js files webpack emits for CSS-only entries
            new RemoveEmptyScriptsPlugin(),
            new MiniCssExtractPlugin({
                filename: '[name].css',
            }),
            ...extraPlugins,
        ],
    };
};
