<!-- Map object group visibility -->
<div class="row no-gutters">
    <div class="col btn-group dropright">
        <button type="button" class="btn btn-accent dropdown-toggle" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-eye"></i>
            <span class="map_controls_element_label_toggle" style="display: none;">
                {{ __('views/common.maps.controls.elements.mapobjectgroupvisibility.toggle_map_elements') }}
            </span>
        </button>
        <div id="map_map_object_group_visibility_dropdown" class="dropdown-menu">
            <!-- Dropdown menu links generated by map.js -->
        </div>
    </div>
</div>
