<?php

return [
    'bolstering'            => [
        'name'        => 'Bolstering',
        'description' => 'When any non-boss enemy dies, its death cry empowers nearby allies, increasing their maximum health and damage by 20%.',
    ],
    'bursting'              => [
        'name'        => 'Bursting',
        'description' => 'When slain, non-boss enemies explode, causing all players to suffer 10% of their max health in damage over 4 sec. This effect stacks.',
    ],
    'explosive'             => [
        'name'        => 'Explosive',
        'description' => 'While in combat, enemies periodically summon Explosive Orbs that will detonate if not destroyed.',
    ],
    'fortified'             => [
        'name'        => 'Fortified',
        'description' => 'Non-boss enemies have 20% more health and inflict up to 30% increased damage.',
    ],
    'grievous'              => [
        'name'        => 'Grievous',
        'description' => 'When injured below 90% health, players will suffer increasing damage over time until healed above 90% health.',
    ],
    'infested'              => [
        'name'        => 'Infested',
        'description' => 'Some non-boss enemies have been infested with a Spawn of G\'huun.',
    ],
    'necrotic'              => [
        'name'        => 'Necrotic',
        'description' => 'All enemies\' melee attacks apply a stacking blight that inflicts damage over time and reduces healing received.',
    ],
    'quaking'               => [
        'name'        => 'Quaking',
        'description' => 'Periodically, all players emit a shockwave, inflicting damage and interrupting nearby allies.',
    ],
    'raging'                => [
        'name'        => 'Raging',
        'description' => 'Non-boss enemies enrage at 30% health remaining, dealing 100% increased damage until defeated.',
    ],
    'relentless'            => [
        'name'        => 'Relentless',
        'description' => 'Non-boss enemies are granted temporary immunity to Loss of Control effects.',
    ],
    'sanguine'              => [
        'name'        => 'Sanguine',
        'description' => 'When slain, non-boss enemies leave behind a lingering pool of ichor that heals their allies and damages players.',
    ],
    'skittish'              => [
        'name'        => 'Skittish',
        'description' => 'Enemies pay far less attention to threat generated by tanks.',
    ],
    'teeming'               => [
        'name'        => 'Teeming',
        'description' => 'Additional non-boss enemies are present throughout the dungeon.',
    ],
    'tyrannical'            => [
        'name'        => 'Tyrannical',
        'description' => 'Boss enemies have 30% more health and inflict up to 15% increased damage.',
    ],
    'volcanic'              => [
        'name'        => 'Volcanic',
        'description' => 'While in combat, enemies periodically cause gouts of flame to erupt beneath the feet of distant players.',
    ],
    'reaping'               => [
        'name'        => 'Reaping',
        'description' => 'Non-boss enemies are empowered by Bwonsamdi and periodically seek vengeance from beyond the grave.',
    ],
    'beguiling'             => [
        'name'        => 'Beguiling',
        'description' => 'Azshara\'s Emissaries are present throughout the dungeon.',
    ],
    'awakened'              => [
        'name'        => 'Awakened',
        'description' => 'Obelisks throughout the dungeon allow players to enter Ny\'alotha and confront powerful servants of N\'Zoth. If a servant is not dealt with, they must be faced during the final boss encounter.',
    ],
    'inspiring'             => [
        'name'        => 'Inspiring',
        'description' => 'Some non-boss enemies have an inspiring presence that strengthens their allies.',
    ],
    'spiteful'              => [
        'name'        => 'Spiteful',
        'description' => 'Fiends rise from the corpses of non-boss enemies and pursue random players.',
    ],
    'storming'              => [
        'name'        => 'Storming',
        'description' => 'While in combat, enemies periodically summon damaging whirlwinds.',
    ],
    'prideful'              => [
        'name'        => 'Prideful',
        'description' => 'Players overflow with pride as they defeat non-boss enemies, eventually forming a Manifestation of Pride. Defeating this Manifestation greatly empowers players.',
    ],
    'tormented'             => [
        'name'        => 'Tormented',
        'description' => 'Servants of the Jailer can be found throughout the dungeon and grant powerful boons when defeated. If a servant is not dealt with, they empower the final boss.',
    ],
    'unknown'               => [
        'name'        => 'Unknown',
        'description' => 'The affixes for this week are not known yet.',
    ],
    'infernal'              => [
        'name'        => 'Infernal',
        'description' => 'Infernal Beacons can be found near some bosses. Activating a Beacon or engaging a nearby boss will trigger a Legion invasion.',
    ],
    'encrypted'              => [
        'name'        => 'Encrypted',
        'description' => 'Enemies throughout the dungeon possess relics of the First Ones. Destroy the relics to summon the First Ones\' Automa and gain powerful bonuses, based on the order in which they were destroyed.',
    ],
    'shrouded'              => [
        'name'        => 'Shrouded',
        'description' => 'Nathrezim infiltrators have disguised themselves among enemies throughout the dungeon. Cartel Ta will reward you handsomely for assisting in their capture.',
    ],
    'thundering'              => [
        'name'        => 'Thundering',
        'description' => 'Enemies have 5% more health. While in combat, players are periodically overcharged with primal power from Raszageth\'s unending storm. This power comes with great risk, and failure to discharge it quickly can have stunning consequences.',
    ],
    'seasonal_index_preset' => '%s preset %d',
];
