history -s 'php artisan combatlog:extractdata tmp'
history -s 'php artisan combatlog:splitchallengemode tmp'
history -s 'php artisan combatlog:splitzonechange tmp'
history -s 'php artisan combatlog:outputcreateroutejson tmp/'
history -s 'php artisan environment:update'
history -s 'php artisan handlebars:refresh'
history -s 'php artisan localization:sync en_US '
history -s 'php artisan mapping:save'
history -s 'php artisan mdt:importmapping '
history -s 'php artisan wowhead:fetchdisplayids '
history -s 'php artisan wowhead:fetchhealth '
history -s 'php artisan wowhead:fetchmissingspellicons'
history -s 'php artisan wowhead:fetchspelldata '
history -s 'php artisan wowhead:refreshdisplayids'
history -s './vendor/bin/phpunit -c phpunit.xml'
history -s './refresh_db_seed.sh'
