<?php
/** @var boolean $isAdmin */
/** @var \Illuminate\Support\Collection $floors */
$enemyVisualType = $_COOKIE['enemy_display_type'] ?? 'enemy_portrait';
$enemyVisualTypes = [
    'enemy_portrait' => __('Portrait'),
    'npc_class' => __('Class'),
    'npc_type' => __('Type'),
    'enemy_forces' => __('Enemy forces'),
];
?>
<nav class="route_manipulation_tools h-100 row align-items-center">
    <div class="p-2 bg-header">
        <!-- Draw controls are injected here through drawcontrols.js -->
        <div id="edit_route_draw_container">


        </div>

        <!-- Draw actions are injected here through drawcontrols.js -->
        <div id="edit_route_draw_actions_container">

        </div>

        <!-- Floor switch -->
        <div id="edit_route_draw_map_actions_container">
            <div class="row">
                <div class="col btn-group dropright">
                    <button type="button"
                            class="btn btn-accent dropdown-toggle {{ $floors->count() > 1 ? '' : 'disabled' }}"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-dungeon"></i>
                    </button>
                    <div id="map_floor_selection_dropdown" class="dropdown-menu">
                        <a class="dropdown-item disabled">
                            {{ __('Floors') }}
                        </a>
                        @foreach($floors as $floor)
                            <a class="dropdown-item {{ $floor->id === $selectedFloorId ? 'active' : '' }}"
                               data-value="{{ $floor->id }}">{{ $floor->name }}</a>
                        @endforeach
                    </div>
                </div>
            </div>

            <!-- Enemy visibility -->
            <div class="row">
                <div class="col btn-group dropright">
                    <button type="button" class="btn btn-accent dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-users"></i>
                    </button>
                    <div id="map_enemy_visuals_dropdown" class="dropdown-menu">
                        <a class="dropdown-item disabled">
                            {{ __('Enemy visual type') }}
                        </a>
                        @foreach($enemyVisualTypes as $value => $text)
                            <a class="dropdown-item {{ $value === $enemyVisualType ? 'active' : '' }}"
                               data-value="{{ $value }}">{{ $text }}</a>
                        @endforeach
                    </div>
                </div>
            </div>

            <!-- Map object group visibility -->
            <div class="row">
                <div class="col btn-group dropright">
                    <button type="button" class="btn btn-accent dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-eye"></i>
                    </button>
                    <div id="map_map_object_group_visibility_dropdown" class="dropdown-menu">
                        <!-- Dropdown menu links generated by map.js -->
                    </div>
                </div>
            </div>

            @if( $isAdmin )
                <div class="row">
                    <div class="col">
                        <label for="map_enemy_visuals_map_mdt_clones_to_enemies">{{ __('MDT') }}</label>
                        <input type="checkbox" class="form-control left_checkbox" value="1"
                               id="map_enemy_visuals_map_mdt_clones_to_enemies"
                               name="map_enemy_visuals_map_mdt_clones_to_enemies"/>
                    </div>
                </div>
            @endif
        </div>
    </div>
</nav>