<?php

namespace Tests\Feature\App\Service\MDT;

use App\Logic\MDT\IO\MDT2Codec;
use App\Models\KillZone\KillZone;
use App\Models\MDTImport;
use App\Service\MDT\MDTImportStringServiceInterface;
use Illuminate\Support\Facades\Artisan;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;

/**
 * Coverage for #3735: MDT 6.2 (WoW 12.1) exports strings in the `!~MDT2~` CBOR format. Import must
 * accept both the legacy `!` format and the new one, producing identical results.
 *
 * The MDT2 fixture carries the exact same preset content as the committed legacy fixture (it was
 * generated by decoding the legacy fixture and re-encoding it with MDT2Codec), so both formats can
 * be compared for equivalence. Comparisons use assertEquals (loose): the legacy path decodes
 * integral Lua numbers as floats where CBOR yields real ints.
 *
 * Equivalence on this fixture pair stops at the decode level: its dungeon (Mists of Tirna Scithe)
 * is no longer MDT-supported, so the full import pipeline rejects it in either format.
 * getDetails/getDungeonRoute equivalence therefore runs on a runtime-exported route for a
 * currently-supported dungeon instead - and, on real client strings, in
 * MDTImportStringServiceMDT2AuthoritativeTest.
 */
#[Group('UsesLua')]
#[Group('MDTImportStringService')]
#[Group('MDT2Codec')]
final class MDTImportStringServiceMDT2Test extends MDTImportStringServiceTestBase
{
    private const LEGACY_FIXTURE = __DIR__ . '/Fixtures/mdt_import_v507_mistsoftirnescithe.txt';

    private const MDT2_FIXTURE = __DIR__ . '/Fixtures/mdt_import_v507_mistsoftirnescithe_mdt2.txt';

    #[Test]
    public function getDecoded_givenMdt2Fixture_returnsSameContentAsLegacyFixture(): void
    {
        // Arrange
        $importStringService = app()->make(MDTImportStringServiceInterface::class);

        // Act
        $legacyDecoded = $importStringService->setEncodedString(file_get_contents(self::LEGACY_FIXTURE))->getDecoded();
        $mdt2Decoded   = $importStringService->setEncodedString(file_get_contents(self::MDT2_FIXTURE))->getDecoded();

        // Assert
        $this->assertIsArray($legacyDecoded);
        $this->assertIsArray($mdt2Decoded);
        $this->assertEquals($legacyDecoded, $mdt2Decoded);
    }

    #[Test]
    public function getDecoded_givenMdt2Fixture_exposesAddonVersion(): void
    {
        // Act - the addonVersion drives mapping-version selection (#3380), so the new format must be
        // able to carry it. Note that MDT 6.2 itself only stamps one on a released build - see
        // MDTImportStringServiceMDT2AuthoritativeTest for what the real client emits.
        $decoded = app()->make(MDTImportStringServiceInterface::class)
            ->setEncodedString(file_get_contents(self::MDT2_FIXTURE))
            ->getDecoded();

        // Assert
        $this->assertSame(507, (int)($decoded['addonVersion'] ?? 0));
    }

    #[Test]
    public function getDungeonRoute_givenReEncodedRuntimeExport_producesSameRouteAsLegacyExport(): void
    {
        $dungeonRoute        = null;
        $legacyString        = null;
        $mdt2String          = null;
        $legacyImportedRoute = null;
        $mdt2ImportedRoute   = null;

        try {
            // Arrange - a runtime-generated route WITH actual pulls, exported through the existing
            // (legacy) export path - empty routes would make the pull/enemy assertions below vacuous
            $dungeonRoute = $this->getMDTCompatibleDungeonRouteWithSafeEnemies();
            $randomEnemy  = $this->getSafeMdtEnemies($dungeonRoute)->first();

            foreach (range(1, 3) as $index) {
                KillZone::factory()->withEnemies($randomEnemy)->create([
                    'dungeon_route_id' => $dungeonRoute->id,
                    'index'            => $index,
                    'description'      => null,
                ]);
            }

            $legacyString = $this->exportDungeonRouteToString($dungeonRoute);

            $importStringService = app()->make(MDTImportStringServiceInterface::class);

            $decoded = $importStringService
                ->setEncodedString($legacyString)
                ->getDecoded();

            // Act - re-encode the same preset into the MDT2 format and run both through the full pipeline
            $mdt2String = (new MDT2Codec())->encode($decoded);

            // getDetails also proves the natively-decoded PHP array marshals into Lua's ValidateImportPreset
            $legacyDetails = $importStringService->setEncodedString($legacyString)->getDetails(collect(), collect());
            $mdt2Details   = $importStringService->setEncodedString($mdt2String)->getDetails(collect(), collect());

            $legacyImportedRoute = $this->importStringToDungeonRoute($legacyString);
            $mdt2ImportedRoute   = $this->importStringToDungeonRoute($mdt2String);

            $legacyImportedRoute->load(['killZones.killZoneEnemies']);
            $mdt2ImportedRoute->load(['killZones.killZoneEnemies']);

            // Assert - our encoder's output is consumable end-to-end and equivalent to the legacy format
            $this->assertEquals($legacyDetails->toArray(), $mdt2Details->toArray());
            $this->assertEquals($legacyImportedRoute->dungeon_id, $mdt2ImportedRoute->dungeon_id);
            $this->assertNotEmpty($legacyImportedRoute->killZones, 'The exported route must have pulls or this test is vacuous');
            $this->assertCount($legacyImportedRoute->killZones->count(), $mdt2ImportedRoute->killZones);
            $this->assertEquals(
                $legacyImportedRoute->killZones->map(fn($killZone) => $killZone->killZoneEnemies->count()),
                $mdt2ImportedRoute->killZones->map(fn($killZone) => $killZone->killZoneEnemies->count()),
            );
        } finally {
            $dungeonRoute?->delete();
            $legacyImportedRoute?->delete();
            $mdt2ImportedRoute?->delete();
            MDTImport::query()->whereIn('import_string', array_filter([$legacyString, $mdt2String]))->delete();
        }
    }

    #[Test]
    #[DataProvider('getDecoded_givenCorruptMdt2String_returnsNull_Provider')]
    public function getDecoded_givenCorruptMdt2String_returnsNull(string $encodedString): void
    {
        // Act
        $decoded = app()->make(MDTImportStringServiceInterface::class)
            ->setEncodedString($encodedString)
            ->getDecoded();

        // Assert
        $this->assertNull($decoded);
    }

    /**
     * @return array<string, array{string}>
     */
    public static function getDecoded_givenCorruptMdt2String_returnsNull_Provider(): array
    {
        return [
            'invalid base64'  => ['!~MDT2~%%%not-base64%%%'],
            'invalid deflate' => [sprintf('!~MDT2~%s', base64_encode('this is not a deflate stream'))],
            'truncated'       => ['!~MDT2~nZjPjxRFFMfBnwvGCAgJBw4d'],
        ];
    }

    #[Test]
    public function mdtDecodeCommand_givenMdt2String_outputsSameContentAsLegacy(): void
    {
        // Act - CLI parity: mdt:decode must handle both formats and produce the same JSON content
        Artisan::call('mdt:decode', ['string' => file_get_contents(self::LEGACY_FIXTURE)]);
        $legacyDecoded = json_decode(trim(Artisan::output()), true);

        Artisan::call('mdt:decode', ['string' => file_get_contents(self::MDT2_FIXTURE)]);
        $mdt2Decoded = json_decode(trim(Artisan::output()), true);

        // Assert
        $this->assertIsArray($legacyDecoded);
        $this->assertEquals($legacyDecoded, $mdt2Decoded);
    }
}
