# Dummy commits done: 0
name: Mapping Deploy

on:
  push:
    branches: development

jobs:
  deploy-mapping:
    runs-on: ubuntu-latest

    steps:
      - name: Update mapping environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: cd /var/www/html/keystone.guru.mapping/;
            php artisan up;
            php artisan down --message "Upgrading Keystone.guru, we will be back stronger than ever shortly!" --retry 60;
            php artisan mapping:save &&
            php artisan mapping:commit &&
            php artisan mapping:merge &&
            php artisan environment:updateprepare &&
            php artisan environment:update mapping;
            php artisan up