# Dummy commits done: 1
name: Mapping Deploy

on:
  push:
    branches: development

jobs:
  deploy-mapping:
    runs-on: ubuntu-latest

    steps:
      - name: Update mapping environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: cd /var/www/html/keystone.guru.mapping/;
            php artisan readonly:enable &&
            php artisan mapping:sync --force=true &&
            php artisan db:backup;
            php artisan up;
            php artisan down --render="errors::503" --retry 60;
            php artisan environment:updateprepare mapping &&
            php artisan environment:update mapping;
            php artisan readonly:disable &&
            php artisan up
