# Dummy commits done: 1
name: Mapping Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to Mapping
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.actor == 'Wotuu'
      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          args: "--ignore-platform-req=ext-lua --ignore-platform-req=ext-zip --ignore-platform-req=ext-pcntl"
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.DEPLOYER_PAT }}"} }'
      - name: Setup Deployer
        uses: atymic/deployer-php-action@0.3.1
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.DEPLOYER_SSH_KNOWN_HOSTS }}
      - name: Deploy
        run: dep deploy mapping.keystone.guru --branch=mapping -vvv
