# Dummy commits done: 1
name: Staging Deploy

on:
  pull_request:
    branches: master

jobs:
  deploy-staging:

    runs-on: ubuntu-latest

    steps:
      - name: Update staging environment
        # Only trigger this pipeline when our source development
        if: github.actor == 'Wotuu'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: cd /var/www/html/keystone.guru.staging/;
            php artisan up;
            php artisan down --render="errors::503" --retry 60;
            php artisan environment:updateprepare &&
            php artisan environment:update staging &&
            php artisan report:release discord;
            php artisan up